#!/bin/bash - 
#===============================================================================
#
#          FILE: quanTriHeThong.sh
# 
#         USAGE: ./quanTriHeThong.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Hoai Nam (), 
#  ORGANIZATION: 
#       CREATED: 28/07/16 08:58
#      REVISION:  ---
#===============================================================================

# Khai bao mot so ham
#Mau do
function red {
	echo -e "\e[31m $1 \e[0m"
}

#Mau do
function yellow {
	echo -e "\e[33m $1 \e[0m"
}

#Mau do
function green {
	echo -e "\e[32m $1 \e[0m"
}

#Title 

function title {
	echo -e "\e[44m\e[1;37m $1 \e[0m"
}

#Error
function error {
	echo -e "\e[41m\e[1;33m $1 \e[0m"
}

#Status

function status {
	echo -e "\e[42m\e[30m $1    |    $2    |    $3 \e[0m"
}
function row {
	echo -e "\e[46m\e[31m $1    |   $2    |   $3 \e[0m"
}
#loading

function loading {
	seq 1 100 | while read i; do echo -en "\e[33m \r....Loading $i%.... \e[0m"; sleep 0.015; done;
	echo -en "\r"
}

function success {
	echo -e "\e[46m\e[31m $1 \e[0m"
}
function subtitle {
	echo -e "\e[45m\e[1;37m $1 \e[0m"
}
function choice1 {
	echo -e "\e[40m\e[1;31m $1 \e[0m"
}
function choice2 {
	echo -e "\e[40m\e[1;32m $1 \e[0m"
}
function choice3 {
	echo -e "\e[40m\e[1;33m $1 \e[0m"
}

#Check Apache
function checkApache {
	if [ "$(dpkg -l | grep apache2)" == "" ]; 
		then
			status "1" "Apache2" "Not Install"
		else
			if [ "$(pidof apache2)" != "" ];
			then
				row "1" "Apache2" "Running"
			else
				row "1" "Apache2" "Stop"	
			fi
		fi
}
#Check Mongo
function checkMongo {
	if [ "$(dpkg -l | grep mongodb)" == "" ]; 
		then
			status "2" "Mongodb" "Not Install"
		else
			if [ "$(pidof mongod)" != "" ];
			then
				row "2" "Mongodb" "Running"
			else
				row "2" "Mongodb" "Stop"	
			fi
		fi
}
#check PHP
function checkPhp {
	if [ "$(dpkg -l | grep php5)" == "" ]; 
		then
			status "3" "PHP5   " "Not Install"
		else
			if [ "$(php -r \phpinfo\(\)\; | grep 'PHP Version')" != "" ];
			then
				row "3" "PHP5   " "Running"
			else
				row "3" "PHP5   " "Stop"	
			fi
		fi
}
#check PHP
function checkSupervisor {
	if [ "$(dpkg -l | grep supervisor)" == "" ]; 
		then
			status "4" "Supervisor" "Not Install"
		else
			if [ "$(pgrep supervisord)" != "" ];
			then
				row "4" "Supervisor" "Running"
			else
				row "4" "Supervisor" "Stop"	
			fi
		fi
}

function installMongo {
	#import Publickey
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 >/dev/null
	#Create list
	echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list >/dev/null
	sudo apt-get update >/dev/null
	sudo apt-get install -y mongodb-org=2.6.9 mongodb-org-server=2.6.9 mongodb-org-shell=2.6.9 mongodb-org-mongos=2.6.9 mongodb-org-tools=2.6.9 </dev/null
	sudo service mongod start >/dev/null
	echo "Cai dat va chay Mongodb thanh cong";
}

function installApache {
	sudo apt-get install apache2 </dev/null
}
function installPhp {
	sudo apt-get install php5-mongo
}
function installSupervisor {
	sudo apt-get install supervisor
	service supervisor restart
}
function info {
	title "DANH SACH CAC DICH VU"
			status "STT" "Ten" "Tinh Trang"
			echo -e "\e[42m\e[30m -------------------------------- \e[0m"
			checkApache
			checkMongo
			checkPhp
			checkSupervisor
			echo ""
}

#ham hien thi bat tat restart
function formBatTat {
				clear
				info
				echo "=============================="
				title "Ban dang chinh sua cho $1"
				echo "=============================="
				subtitle "Nhap yeu cau muon chinh sua"
				echo "______________________________"
				choice1 "1 - Bat"
				choice2 "2 - Tat"
				choice3 "3 - Khoi dong lai"
				error "4 - Tro ve"
				echo "______________________________"		
				read choice
				if [ "$choice" == 1 ]; then
					#statements
					sudo service $1 start >/dev/null
					success "Ban da bat dich vu $1 thanh cong"
					echo ""
				elif [ "$choice" == 2 ]; then
						#statements	
					sudo service $1 stop >/dev/null	
					success "Ban da tat dich vu $1 thanh cong"
					echo ""
				elif [ "$choice" == 3 ]; then
							#statements	
					sudo service $1 restart	>/dev/null
					success "Ban da khoi dong lai dich vu $1 thanh cong"
					echo ""
				elif [ "$choice" == 4 ]; then
					#statements						
					clear
				fi
}


function table {
	echo "=============================="
	echo "+                             +"
	echo "+                             +"
	echo "+                             +"
	echo "+                             +"
	echo "=============================="
}
#Ham check ton tai
function checkWeb {
	cd /etc/apache2/sites-enabled/
	if [ -f $1.conf ]; then
		#statements
		status="Bat"
	else
		status="Tat"	
	fi
}

#In website
function row2 {
	if [ "$status" == "Bat" ]; then
		#statements
		echo -e "\e[40m\e[37m $1     |    $2            |    $3 \e[0m"
	else
		echo -e "\e[45m\e[37m $1     |    $2            |    $3 \e[0m"
	fi
}

function formBatTatWebsite {
				clear
				HienThiWebsite
				echo "=============================="
				title "Ban dang chinh sua cho website $1"
				echo "=============================="
				subtitle "Nhap yeu cau muon chinh sua"
				echo "______________________________"
				choice1 "1 - Bat"
				choice2 "2 - Tat"
				choice3 "3 - Xoa"
				choice3 "4 - Thay doi ten mien"
				error "3 - Tro ve"
				echo "______________________________"		
				read choice
				if [ "$choice" == 1 ]; then
					#statements
					sudo a2ensite $1 >/dev/null
					sudo service apache2 reload >/dev/null
					success "Ban da bat website $1 thanh cong"
					echo ""
				elif [ "$choice" == 2 ]; then
						#statements	
					sudo a2dissite $1 >/dev/null
					sudo service apache2 reload >/dev/null
					success "Ban da tat website $1 thanh cong"
					echo ""
				elif [ "$choice" == 3 ]; then
					#statements
					success "Ban co chac chan muon xoa Website va Nguoi dung nay ko? (Y/N)"
					read
					if [ "${REPLY^^}" == "Y" ]; then
						userdel -r $1
						removeSite $1
					else
						clear
					fi					
					clear
				elif [ "$choice" == 4 ]; then
					#statements
					cd /etc/apache2/sites-available
					echo "ServerName hien tai cua ban: "
					cat $1.conf | grep "ServerName"
					subtitle "Moi ban nhap ServerName thay the (Nhan 'q' de thoat)"
					read 
					if [ "$REPLY" == "q" ]; then
							#statements
						clear
					else
					cat $1.conf | awk '{ r = gensub(/ServerName (.+)/, "ServerName: '$REPLY'", "g"); print r; }' >a.conf
					rm $1.conf
					mv a.conf $1.conf
					success "Doi sername thanh cong"		
					fi						
					clear
				elif [ "$choice" == 5 ]; then
					#statements						
					clear		
				fi
}
function HienThiWebsite {
			title "Danh sach cac website"
			echo ""
			cd /etc/apache2/sites-available/
			danhsach=($(ls | cut -d"." -f1))
		#Hien thi danh sach cac webstie
			status "STT" "Website" "Tinh trang"
			STT=1
			for i in "${danhsach[@]}"
			do
				checkWeb $i
				row2 $STT $i $status
				STT=$(expr $STT + 1)

			   # do whatever on $i
			done
}

function removeSite {
		a2dissite $1 >/dev/null
		cd /etc/apache2/sites-available
		rm $1.conf
}
#Main
function main {
	title "-------> Quan Tri He Thong <---------"
PS3="-->> "
options=("Xem thong tin he thong" "Thiet lap moi truong" "Quan ly dich vu" "Quan ly Website" "Phan quyen" "Tro Lai")
select opt in "${options[@]}";
do
	case $opt in
		"Xem thong tin he thong")
		#In tieu de
		title "Xem thong tin cua he thong"
		loading
		status "STT" "Ten" "Tinh Trang"
		echo -e "\e[42m\e[30m -------------------------------- \e[0m"
		#Kiem tra tinh trang
		# Kiem tra apache da cai dat chua va tinh trang
		checkApache
		#Check database mongo
		checkMongo
		#Check PHP5
		checkPhp
		#CheckSupervisor
		checkSupervisor
		;;
		"Thiet lap moi truong")
		#kiem tra moi truong cai dat va xu ly
		#Kiem tra moi truong
		
		if [ \("$(dpkg -l | grep apache2)" == ""\) -o \("$(dpkg -l | grep mongodb)" == ""\) -o \("$(dpkg -l | grep php5)" == ""\) -o \("$(dpkg -l | grep supervisor)" == ""\) ]; 
		then
			title "Thiet lap moi truong he thong"
			loading
			error "Moi truong chua duoc cai dat hoan thien"
			echo ""
			yellow "----->Ban co muon cai dat cac pakage thieu khong? - Y/N <------"
			read 
			if [ "${REPLY^^}" == "Y" ]; then
				#statements
				if [ "$(dpkg -l | grep apache2)" == "" ]; then
					installApache
				fi
				if [ "$(dpkg -l | grep mongodb)" == "" ]; then
					#statements
					installMongo
				fi
				if [ "$(dpkg -l | grep php5)" == "" ]; then
					#statements
					installPhp
				fi
				if [ "$(dpkg -l | grep supervisor)" == "" ]; then
					#statements
					installSupervisor
				fi
				clear
				success "Cai dat thanh cong"
				main
			else
				error "Huy bo thao tac"
			fi
		else
			success "Moi truong da duoc cai dat day du cac dich vu"

		fi	

		;;
		"Quan ly dich vu")
		title "Quan ly dich vu"
		check=0
			while [ "$check" == "0" ]; do
				#statements
			clear
			info
			subtitle "Nhap dich vu muon chinh sua (Go '5' de tro ve menu): "
			PS3="Moi ban nhap: "
			read service
			if [ "$service" == "1" ]; then
				#statements
				formBatTat apache2

			elif [ "$service" == "2" ]; then
					#statements
					formBatTat mongodb
			elif [ "$service" == "3" ]; then
							#statements
					formBatTat apache2			
			elif [ "$service" == "4" ]; then
				#statements
					formBatTat supervisor
			elif [ "$service" == "5" ]; then
				#statements
					check=1
					clear
					main		
			else
				error "Nhap sai moi nhap lai!";
				echo ""	
			fi
			done

		;;
		"Quan ly Website")
		dem=0
		while [ "$dem" == "0" ]; do
			#statements
			#Hien thi website
			HienThiWebsite
		#Choice
			echo ""
			title "Nhap webstie muon chinh sua (Go 'back' de tro ve menu): "
			PS3="Moi ban nhap: "
			read 
			if [ "$REPLY" == "back" ]; then
					#statements	
					clear
					dem=1
					main 
			elif [ "${danhsach[$(expr $REPLY - 1)]}"  != "" ]; then
				#statements
				formBatTatWebsite ${danhsach[$(expr $REPLY - 1)]}
			
			fi
			
		done
		;;
		"Phan quyen")


		;;
		"Tro Lai")
		clear
		break

		;;
	*) error "Moi ban nhap lai"
	esac
done	
}

#Run main
main

				
